version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "msal-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10twfa2tm35u"
s3_prefix = "msal-demo"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
