AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  Authority:
    Type: String
  ClientID:
    Type: String
  ClientSecret:
    Type: String
Resources:
  HttpApiGateway:
    Type: AWS::Serverless::HttpApi
  HttpApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./deploy/lambda_package.zip
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Timeout: 60
      Environment:
        Variables:
          AUTHORITY: !Ref Authority
          CLIENT_ID: !Ref ClientID
          CLIENT_SECRET: !Ref ClientSecret
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:DeleteItem
                - dynamodb:GetItem
                - dynamodb:Query
              Resource:
                - arn:aws:dynamodb:*:*:table/lambda_sessions/index/*
                - arn:aws:dynamodb:*:*:table/lambda_sessions
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApiGateway
            Method: ANY
            Path: /{proxy+}
Outputs:
  HttpApiUrl:
    Value: !Sub "https://${HttpApiGateway}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
  HttpApiFunction:
    Value: !Ref HttpApiFunction
